### ISSUE TITLE
How do identify the code status for patients?

### ISSUE THREAD

**Issue by joytywu** [mimic2/v2.6#1]
I am not sure which mimic2v2.6 table have the code status information for patients (e.g. DNR, CMO, etc)

**Comment by tompollard** [comment]
Hi Joy, please see: https://mimic.physionet.org/database/faqs.html#18. Essentially you need to:

1) find itemid for label "code status":

``` sql
-- find itemid for label "code status"
select itemid
  from mimic2v26.d_chartitems
where lower(label) like '%code%';
```
2) which allows you to extract all chartevents for 'code status':
``` sql
-- find all chartevents where itemid = 128
select *
from mimic2v26.chartevents
where itemid = '128';
```
3) You can then run a search for your status of interest: 
``` sql
-- find all chartevents where itemid = 128 and value1 = comfort measures (CMO)
select *
from mimic2v26.chartevents
where itemid = '128' and lower(value1) like '%comfort%';
```

**Comment by joytywu** [comment]
Thanks Tom!

Joy
